name: Feature request
description: Suggest features, propose improvements, discuss new ideas.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: >
        Before requesting please search [existing issues](https://github.com/TheAlgorithms/Python/labels/enhancement).
        Usage questions such as "How do I...?"  belong on the
        [Discord](https://discord.gg/c7MnfGFGa6) and will be closed.

  - type: textarea
    attributes:
      label: "Feature description"
      description: >
        This could be new algorithms, data structures or improving any existing
        implementations.
    validations:
      required: true
